### PR TITLE
Refactor viewpoint and reaction endpoint response

### PR DESCRIPTION
**Pull request by YukinaMochizuki**
## Type of changes
Refacotr

### Add ViewPointReaction schema
Incorporate the ViewPointReaction response schema into the following endpoints:
- /api/viewpoint/{id}/like/me
- /api/viewpoint/{id}/reasonable/me
- /api/viewpoint/{id}/dislike/me

By replying with a ViewPointReaction schema, that enable the frontend to easily identify and display the current reaction status (like, reasonable, dislike) after these endpoint responsed.

### Embed Facts into the schema of the Viewpoint
The new optimization strategy aims to minimize API requests by delivering all required data in a single response rather than multiple queries. The first page loads only the content visible on the device screen, with the second page preloading immediately after the first is fully loaded.

To achieve the above purpose, the Fact Schema is embedded within the Viewpoint Schema.

### ViewPointReaction
```mermaid
classDiagram
  class ViewPointReaction {
    int likeCount 
    int ReasonableCount 
    int dislikeCount
    boolean userLiked 
    boolean userReasonable
    boolean userDisliked 
  }
```

### ViewPoint
Add

```mermaid
classDiagram
  class ViewPoint {
    boolean userLiked 
    boolean userReasonable
    boolean userDisliked 
    list[fact] facts
  }

### CODE REVIEW

**Comment by burnedinthesky** [comment]
It seems there are some functionalities missing and some inefficiencies regarding specific endpoints. Here are the most severe issues

- Lacks ability to get viewpoint for specific issue
I currently only see the endpoint `/api/viewpoints`, which although the frontend team can just filter out viewpoints not related to the current issue, there are severe drawbacks to this approach. For example, we would always need to request all viewpoints which exist in the DB to ensure we've gotten every viewpoint related to the issue currently being viewed. We also get an inconsistent number of viewpoints being displayed each time (since sometimes maybe 3/10 of the viewpoints returned are related to the current issue, and other times 6/10, the user will always see a random number of new issues appear when lazy scrolling)

- Impossible scenario in sample data for endpoint `/api/viewpoint/id`
  It is impossible for all userLiked, userReasonable, userDisliked to be true at the same time 

- Endpoint `/api/viewpoint/{id}/[likes/reasonables/dislikes]` should not exist
  I am assuming the auth level required for this endpoint is user. This implies that any user can see what posts other users have liked, making it incredibly damaging to users' privacy.

**Comment by burnedinthesky** [comment]
I am also concerned by the inefficiencies in the current design. As a general request, it would much be preferred if the backend would fetch all sub-table data for us. For example, to include all related reference favicons and urls when providing facts, and providing all related facts (including references) when requesting viewpoints. This is mainly to reduce the amount of requests needed to be sent to the backend. Since, for example, when viewing an issue, assuming 10 issues per viewpoint pagination fetch, 3 facts per viewpoint, and 2 references per fact. The frontend would first make 1 request to get the 10 issues, then make 10 requests to get all facts for the 10 viewpoints, and then another 30 requests to get all references for the 30 facts. This results in 41 requests and 3 round-trip time delays total. The alternative approach, combining all info into one request results in 1 request and 1 round-trip time delay, containing the same amount data. 

The specific endpoints I hope are refactored are 
- /api/viewpoints
- /api/viewpoint/{id}
- /api/viewpoint/{id}/facts
- /api/facts [both GET and POST]
- /api/fact/{id}

The same logic applies to creation too, specifically fact creation. The current fact creation requires the frontend to do 1+n requests
- POST to `/api/facts`, await for response for fact id
- POST n (the number of references) times to /api/fact/{id}/references

It would be much easier if we could just include the reference data while posting to `/api/facts`

**Comment by burnedinthesky** [comment]
Lastly, out of curiosity, why not just merge `/api/viewpoint/{id}/[like/reasonable/dislike]/me` into a single api, and take the reaction in the POST body?

**Review by burnedinthesky — CHANGES_REQUESTED** [review]
Please fix all aforementioned issues

**Comment by YukinaMochizuki** [comment]
@burnedinthesky

Thanks for reviewing and raising questions. This is my first time designing the API for a social platform, so if you think of any other areas that need discussion, please feel free to bring them up! 

> Lacks ability to get viewpoint for specific issue

> There is no viewpoint creation endpoint

Listing all viewpoints is very useful for internal statistics or data analysis. Since it's a fundamental endpoint, I plan to handle it along with the implementation of the viewpoint feature. This endpoint is intended for internal use only, and I will include relevant descriptions in the upcoming commit.

In the future Issue API pull request (PR), I will further update the Issue endpoints, including:

```
GET | POST /api/issue/{id}/viewpoints
```

to retrieve all viewpoints under an issue and to create a viewpoint within a specific issue. Since viewpoints currently don't exist independently of issues, there is no POST method designed for /api/viewpoints.


> Endpoint /api/viewpoint/{id}/[likes/reasonables/dislikes] should not exist
> 
> I am assuming the auth level required for this endpoint is user. This implies that any user can see what posts other users have liked, making it incredibly damaging to users' privacy.

I don't believe it's necessary to elevate this to a "damaging" user privacy issue. Many social media platforms allow access to lists of users who have liked or reacted by default, and we currently have no privacy policy that addresses this specifically. However, since neither our current Figma designs nor use cases include this feature, I will remove the related API.

> I am also concerned by the inefficiencies in the current design. As a general request, it would much be preferred if the backend would fetch all sub-table data for us ...
> 
> The specific endpoints I hope are refactored are
> /api/viewpoints
> /api/viewpoint/{id}
> /api/viewpoint/{id}/facts
> /api/facts [both GET and POST]
> /api/fact/{id}

The current design allows the frontend to simply use `GET /api/issue/{id}/viewpoints` to retrieve the list of `viewpoints`, with `facts` and `reference` included in the response. This way, a single request is sufficient, and the backend will utilize eager loading and caching to avoid the N+1 query issue.

See: 
https://github.com/commonground-project/api/blob/6844b788d47ba8b4467350a43aa9f6f8ee90372b/schemas/viewpoint.yaml#L47-L50

Due to some timing discrepancies in the design, `reference` was not included in the `fact` data structure. I will address this issue in an upcoming commit. However, it should look something like this:

```yaml
Fact:
  type: object
  properties:

    # other properties...

    facts:
      type: array
      items:
        $ref: "../schemas/reference.yaml#/Reference"
```

### Action Items

For the other viewpoints that I also agree with, I have consolidated the necessary action items below:

> Impossible scenario in sample data for endpoint /api/viewpoint/id

> There is no method to remove a reaction (e.g., retract liking a viewpoint)
- Refactor reaction into an enum with the following values: `LIKE`, `REASONABLE`, `DISLIKE`, and `NONE`
  - Refactor the reaction in the Viewpoint schema into a single field
  - Refactor `/viewpoint/{id}/[like/reasonable/dislike]/me` to `/viewpoint/{id}/reaction/me`, and use the `reaction` in the body to determine what action to take

> It would be much easier if we could just include the reference data while posting to /api/facts
- Add a reference list to the request for `POST /api/facts` to avoid the need for multiple requests to complete the creation of a fact

### Other Action Items
#### In this PR
- Remove the API for retrieving the list of users who reacted

#### In follow-up PR
- Add permission descriptions for each API

**Review by burnedinthesky — CHANGES_REQUESTED** [review]
@YukinaMochizuki 

Thanks for your detailed response, most of my concerns have been addressed in the update. However, I've been looking at the new API and found some minor typos in the template responses.

> GET `/issue/{id}/viewpoints`
- `ReasonableCount` should be `reasonableCount`
- `facts -> createAt` should be `facts -> createdAd`
- `facts -> references -> createAt` should be `facts -> references -> createdAt`
- Lacks the author's avatar URL

> POST `/issue/{id}/viewpoints`

I was wondering if it is possible for fact uploads to be type of `fact_id | new_fact`. Since if is both possible to cite an existing fact and create a new fact, the current workflow requires the frontend to wait at least two RTTs (round-trip time) before the issue can be created (one for fact creation to get fact ids, one for issue creation). I think it would be faster & more reliable if it were merged into one API call.

> PUT `/api/viewpoint/{id}`

I'm not sure if this is a consensus but I personally think which facts are cited should be modifiable too. If @YukinaMochizuki agrees too I believe the endpoint needs to have the same fact input fields as `POST /issue/{id}/viewpoints`

> POST `/api/viewpoint/{id}/reaction/me`

The swagger documentation may need to document the four exact values the enum expects, as it's a bit inefficient to have to checkout this issue for documentation. 

Lastly, as general feedback, I think it would be greatly beneficial if the documentation on swagger were more accurate. For example, in the route `/api/viewpoint/{id}`, the description says "This endpoint returns specific fact information by fact id", and the id field is ambiguously described as "The uuid of request".

**Comment by YukinaMochizuki** [comment]
@burnedinthesky

Thank you for carefully reviewing the typo in the PR. I have fixed them and standardized the style to camel case to align with Java and React conventions.

> `POST /issue/{id}/viewpoints`
> I was wondering if it is possible for fact uploads to be type of fact_id | new_fact ...

I believe merging the responsibility of creating `Facts` into the `Post Viewpoints` process could lead to potential user experience and performance issues.

Specifically, according to our [v0.1 Figma design](https://www.figma.com/design/LM1cxbnjfLqwSMvQAR9GrY/V0.1?node-id=0-1&t=3bHL2905m69nrCdR-1), users can click "引入一項事實" while creating a Viewpoint to enter the `Fact` creation screen.

image

Then, they can click "建立" to establish a new `Fact`.

image

If the `Fact` is not actually created at this point, it may lead to a discrepancy between the user's perception and the system's actual state. This is especially problematic if the Fact creation fails (e.g., due to an invalid URL format, a non-existent website, or a link flagged as unsafe on our blacklist). Such errors would only be reported after the user completes and submits the entire `Viewpoint`, causing the `Viewpoint` creation to fail altogether.

For the user, this could be quite frustrating. Therefore, I think it would be better to report any relevant errors as early as possible.

From a performance perspective, each `Fact` contains multiple `References`, and the icons and titles within each `Reference` are external resources when the site is first indexed. The backend needs time to fetch. If a large number of sites are indexed at once and some have slow response times, this could significantly block the `POST Viewpoints` request. Without a loading indicator, users may perceive the system as unresponsive.

>  I believe the endpoint needs to have the same fact input fields as `POST /issue/{id}/viewpoints`

Agree and added, tks.

> The swagger documentation may need to document the four exact values the enum expects, as it's a bit inefficient to have to checkout this issue for documentation.

All possible enums are documented here:

https://github.com/commonground-project/api/blob/177b2316a7439959bba74adedbda4ef130382a4a/schemas/viewpoint.yaml#L51-L59

And I added a schemas component in OpenAPI, so the definitions can be directly presented in Swagger, like this:

image

**Review by burnedinthesky — APPROVED** [review]
@YukinaMochizuki Thanks for the updates. I believe the API is now ready to be integrated!

**Pull request merged**
